include:
  - app.yaml
services:
  caddy:
    image: caddy:alpine
    container_name: 68-s1-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - s1app

volumes:
  caddy_data:
  caddy_config:
